#!/bin/sh

SCRIPT_DIR=`dirname $0`
if [ -f "${SCRIPT_DIR}/pms_tool.conf" ]; then
    . "${SCRIPT_DIR}/pms_tool.conf"
else
    echo "no pms_tool.conf."
    exit 1
fi

WID=`uuidgen`
TMPFILE=/tmp/$WID

if [ $# -eq 0 ]; then 
	echo "Give me Device GroupName" >&2
	exit 1 
else
	GROUPNAME="$1"
fi

sudo "$PSQL" -U $DBUSER -h "$DBHOST" $DBNAME \
 -c 'select id,name from device_groups  ;' > ${TMPFILE}-1

awk '-F|' -v G="$GROUPNAME" '$2 == " "G { print $1}'  ${TMPFILE}-1  | awk '$1 = $1'

rm  ${TMPFILE}-1
