#!/bin/sh

SCRIPT_DIR=`dirname $0`
if [ -f "${SCRIPT_DIR}/pms_tool.conf" ]; then
    . "${SCRIPT_DIR}/pms_tool.conf"
else
    echo "no pms_tool.conf."
    exit 1
fi

cd /tmp
sudo $SUDO_OPT "$PSQL" -U $DB_FILE_OWNER -h "$DBHOST" --list
cd - > /dev/null 2>&1
