#!/bin/sh

SCRIPT_DIR=`dirname $0`
if [ -f "${SCRIPT_DIR}/pms_tool.conf" ]; then
    . "${SCRIPT_DIR}/pms_tool.conf"
else
    echo "no pms_tool.conf."
    exit 1
fi

if [ $# -eq 0 ]; then 
	echo "Give me Device HW SerialNumber." >&2
	exit 1 
else
	HWSERIAL="$1"
fi

sudo "$PSQL" -U $DBUSER -h "$DBHOST" $DBNAME \
 -c "select id from devices where \"SerialNumber\" = '$HWSERIAL' ;" | awk 'NR == 3' | awk '$1 = $1' | grep -v row
