#!/bin/sh

TIMES=`date +%Y%m%d-%H%M%S`

if [ ! -d $HOME/Documents/pms01.dena.com/groupinfo ]; then
	mkdir -p $HOME/Documents/pms01.dena.com/groupinfo
fi

for G in `$HOME/bin/pms_get_devicegrouplist | awk '{print $3}' | grep -v "JP-VPN" | grep -iv DeNA | grep -v name | grep -v Test | grep -v 1-For `
do
	$HOME/bin/pms_get_devicemembers_of_group $G > $HOME/Documents/pms01.dena.com/groupinfo/${G}_${TIMES}
done
