#!/bin/sh

SCRIPT_DIR=`dirname $0`
if [ -f "${SCRIPT_DIR}/pms_tool.conf" ]; then
    . "${SCRIPT_DIR}/pms_tool.conf"
else
    echo "no pms_tool.conf."
    exit 1
fi

DUMPDIR=$1

if [ "${DUMPDIR}"X = X ]; then DUMPDIR=/var/tmp/ ;fi
if [ ! -d "${DUMPDIR}" ]; then DUMPDIR=/var/tmp/ ;fi

DUMPFILE="${DUMPDIR}/${DBNAME}_pg_dump_`date +%Y%m%d-%H%M%S`"

sudo $PGDUMP -U $DBUSER -h "$DBHOST" "$DBNAME" | gzip > "${DUMPFILE}.gz"
ls -l "${DUMPFILE}.gz"
